wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.11
    framework: xgboost
    huggingface_version: 4.17.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.12
    start_time: 1748642335
    t:
      1:
      - 1
      - 5
      - 6
      - 11
      - 49
      2:
      - 1
      - 5
      - 6
      - 11
      - 49
      3:
      - 13
      - 16
      4: 3.8.12
      5: 0.12.11
      6: 4.17.0
      8:
      - 3
      - 5
config:
  desc: null
  value: src/conf/toy.yaml
inherit:
  desc: null
  value:
  - C:\Users\aruna\Downloads\in-context-learning-main\src\conf\models\standard.yaml
  - C:\Users\aruna\Downloads\in-context-learning-main\src\conf\wandb.yaml
model:
  desc: null
  value:
    family: gpt2
    n_dims: 5
    n_embd: 256
    n_head: 8
    n_layer: 12
    n_positions: 11
out_dir:
  desc: null
  value: ../models/linear_regression\ef25ece3-db96-4f08-a11b-6e6af2b3f6cf
test_run:
  desc: null
  value: false
training:
  desc: null
  value:
    batch_size: 64
    curriculum:
      dims:
        end: 5
        inc: 1
        interval: 2000
        start: 5
      points:
        end: 11
        inc: 2
        interval: 2000
        start: 11
    data: gaussian
    keep_every_steps: 100000
    learning_rate: 0.0001
    num_tasks: null
    num_training_examples: null
    resume_id: null
    save_every_steps: 1000
    task: linear_regression
    task_kwargs: {}
    train_steps: 5001
wandb:
  desc: null
  value:
    entity: arun_akashr-texas-a-m-universit
    log_every_steps: 100
    name: linear_regression_toy
    notes: ''
    project: in-context-training
