config: src/conf/toy.yaml
inherit:
- C:\Users\aruna\Downloads\in-context-learning-main\src\conf\models\standard.yaml
- C:\Users\aruna\Downloads\in-context-learning-main\src\conf\wandb.yaml
model:
  family: gpt2
  n_dims: 5
  n_embd: 256
  n_head: 8
  n_layer: 12
  n_positions: 11
out_dir: ../models/linear_regression\ef25ece3-db96-4f08-a11b-6e6af2b3f6cf
test_run: false
training:
  batch_size: 64
  curriculum:
    dims:
      end: 5
      inc: 1
      interval: 2000
      start: 5
    points:
      end: 11
      inc: 2
      interval: 2000
      start: 11
  data: gaussian
  keep_every_steps: 100000
  learning_rate: 0.0001
  num_tasks: null
  num_training_examples: null
  resume_id: null
  save_every_steps: 1000
  task: linear_regression
  task_kwargs: {}
  train_steps: 5001
wandb:
  entity: arun_akashr-texas-a-m-universit
  log_every_steps: 100
  name: linear_regression_toy
  notes: ''
  project: in-context-training
